// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.29.1
// source: listener.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Listener_Protocol int32

const (
	Listener_MCP Listener_Protocol = 0
	Listener_A2A Listener_Protocol = 1
)

// Enum value maps for Listener_Protocol.
var (
	Listener_Protocol_name = map[int32]string{
		0: "MCP",
		1: "A2A",
	}
	Listener_Protocol_value = map[string]int32{
		"MCP": 0,
		"A2A": 1,
	}
)

func (x Listener_Protocol) Enum() *Listener_Protocol {
	p := new(Listener_Protocol)
	*p = x
	return p
}

func (x Listener_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Listener_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_listener_proto_enumTypes[0].Descriptor()
}

func (Listener_Protocol) Type() protoreflect.EnumType {
	return &file_listener_proto_enumTypes[0]
}

func (x Listener_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Listener_Protocol.Descriptor instead.
func (Listener_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_listener_proto_rawDescGZIP(), []int{0, 0}
}

type Listener struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol Listener_Protocol `protobuf:"varint,2,opt,name=protocol,proto3,enum=agentgateway.dev.listener.Listener_Protocol" json:"protocol,omitempty"`
	// Types that are assignable to Listener:
	//
	//	*Listener_Sse
	//	*Listener_Stdio
	Listener isListener_Listener `protobuf_oneof:"listener"`
}

func (x *Listener) Reset() {
	*x = Listener{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listener_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listener) ProtoMessage() {}

func (x *Listener) ProtoReflect() protoreflect.Message {
	mi := &file_listener_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listener.ProtoReflect.Descriptor instead.
func (*Listener) Descriptor() ([]byte, []int) {
	return file_listener_proto_rawDescGZIP(), []int{0}
}

func (x *Listener) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Listener) GetProtocol() Listener_Protocol {
	if x != nil {
		return x.Protocol
	}
	return Listener_MCP
}

func (m *Listener) GetListener() isListener_Listener {
	if m != nil {
		return m.Listener
	}
	return nil
}

func (x *Listener) GetSse() *SseListener {
	if x, ok := x.GetListener().(*Listener_Sse); ok {
		return x.Sse
	}
	return nil
}

func (x *Listener) GetStdio() *StdioListener {
	if x, ok := x.GetListener().(*Listener_Stdio); ok {
		return x.Stdio
	}
	return nil
}

type isListener_Listener interface {
	isListener_Listener()
}

type Listener_Sse struct {
	Sse *SseListener `protobuf:"bytes,3,opt,name=sse,proto3,oneof"`
}

type Listener_Stdio struct {
	Stdio *StdioListener `protobuf:"bytes,4,opt,name=stdio,proto3,oneof"`
}

func (*Listener_Sse) isListener_Listener() {}

func (*Listener_Stdio) isListener_Listener() {}

type SseListener struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The address of the listener.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// The port of the listener.
	Port  uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Tls   *SseListener_TlsConfig `protobuf:"bytes,3,opt,name=tls,proto3" json:"tls,omitempty"`
	Authn *SseListener_Authn     `protobuf:"bytes,4,opt,name=authn,proto3" json:"authn,omitempty"`
	Rbac  []*RuleSet             `protobuf:"bytes,5,rep,name=rbac,proto3" json:"rbac,omitempty"`
}

func (x *SseListener) Reset() {
	*x = SseListener{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listener_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SseListener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SseListener) ProtoMessage() {}

func (x *SseListener) ProtoReflect() protoreflect.Message {
	mi := &file_listener_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SseListener.ProtoReflect.Descriptor instead.
func (*SseListener) Descriptor() ([]byte, []int) {
	return file_listener_proto_rawDescGZIP(), []int{1}
}

func (x *SseListener) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SseListener) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SseListener) GetTls() *SseListener_TlsConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *SseListener) GetAuthn() *SseListener_Authn {
	if x != nil {
		return x.Authn
	}
	return nil
}

func (x *SseListener) GetRbac() []*RuleSet {
	if x != nil {
		return x.Rbac
	}
	return nil
}

type StdioListener struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StdioListener) Reset() {
	*x = StdioListener{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listener_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StdioListener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdioListener) ProtoMessage() {}

func (x *StdioListener) ProtoReflect() protoreflect.Message {
	mi := &file_listener_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdioListener.ProtoReflect.Descriptor instead.
func (*StdioListener) Descriptor() ([]byte, []int) {
	return file_listener_proto_rawDescGZIP(), []int{2}
}

type SseListener_TlsConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyPem  *LocalDataSource `protobuf:"bytes,1,opt,name=key_pem,json=keyPem,proto3" json:"key_pem,omitempty"`
	CertPem *LocalDataSource `protobuf:"bytes,2,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
}

func (x *SseListener_TlsConfig) Reset() {
	*x = SseListener_TlsConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listener_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SseListener_TlsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SseListener_TlsConfig) ProtoMessage() {}

func (x *SseListener_TlsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_listener_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SseListener_TlsConfig.ProtoReflect.Descriptor instead.
func (*SseListener_TlsConfig) Descriptor() ([]byte, []int) {
	return file_listener_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SseListener_TlsConfig) GetKeyPem() *LocalDataSource {
	if x != nil {
		return x.KeyPem
	}
	return nil
}

func (x *SseListener_TlsConfig) GetCertPem() *LocalDataSource {
	if x != nil {
		return x.CertPem
	}
	return nil
}

type SseListener_Authn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jwt *SseListener_Authn_JwtConfig `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
}

func (x *SseListener_Authn) Reset() {
	*x = SseListener_Authn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listener_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SseListener_Authn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SseListener_Authn) ProtoMessage() {}

func (x *SseListener_Authn) ProtoReflect() protoreflect.Message {
	mi := &file_listener_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SseListener_Authn.ProtoReflect.Descriptor instead.
func (*SseListener_Authn) Descriptor() ([]byte, []int) {
	return file_listener_proto_rawDescGZIP(), []int{1, 1}
}

func (x *SseListener_Authn) GetJwt() *SseListener_Authn_JwtConfig {
	if x != nil {
		return x.Jwt
	}
	return nil
}

type SseListener_Authn_JwtConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Issuer   []string `protobuf:"bytes,1,rep,name=issuer,proto3" json:"issuer,omitempty"`
	Audience []string `protobuf:"bytes,2,rep,name=audience,proto3" json:"audience,omitempty"`
	// Types that are assignable to Jwks:
	//
	//	*SseListener_Authn_JwtConfig_LocalJwks
	//	*SseListener_Authn_JwtConfig_RemoteJwks
	Jwks isSseListener_Authn_JwtConfig_Jwks `protobuf_oneof:"jwks"`
}

func (x *SseListener_Authn_JwtConfig) Reset() {
	*x = SseListener_Authn_JwtConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listener_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SseListener_Authn_JwtConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SseListener_Authn_JwtConfig) ProtoMessage() {}

func (x *SseListener_Authn_JwtConfig) ProtoReflect() protoreflect.Message {
	mi := &file_listener_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SseListener_Authn_JwtConfig.ProtoReflect.Descriptor instead.
func (*SseListener_Authn_JwtConfig) Descriptor() ([]byte, []int) {
	return file_listener_proto_rawDescGZIP(), []int{1, 1, 0}
}

func (x *SseListener_Authn_JwtConfig) GetIssuer() []string {
	if x != nil {
		return x.Issuer
	}
	return nil
}

func (x *SseListener_Authn_JwtConfig) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (m *SseListener_Authn_JwtConfig) GetJwks() isSseListener_Authn_JwtConfig_Jwks {
	if m != nil {
		return m.Jwks
	}
	return nil
}

func (x *SseListener_Authn_JwtConfig) GetLocalJwks() *LocalDataSource {
	if x, ok := x.GetJwks().(*SseListener_Authn_JwtConfig_LocalJwks); ok {
		return x.LocalJwks
	}
	return nil
}

func (x *SseListener_Authn_JwtConfig) GetRemoteJwks() *RemoteDataSource {
	if x, ok := x.GetJwks().(*SseListener_Authn_JwtConfig_RemoteJwks); ok {
		return x.RemoteJwks
	}
	return nil
}

type isSseListener_Authn_JwtConfig_Jwks interface {
	isSseListener_Authn_JwtConfig_Jwks()
}

type SseListener_Authn_JwtConfig_LocalJwks struct {
	LocalJwks *LocalDataSource `protobuf:"bytes,3,opt,name=local_jwks,json=localJwks,proto3,oneof"`
}

type SseListener_Authn_JwtConfig_RemoteJwks struct {
	RemoteJwks *RemoteDataSource `protobuf:"bytes,4,opt,name=remote_jwks,json=remoteJwks,proto3,oneof"`
}

func (*SseListener_Authn_JwtConfig_LocalJwks) isSseListener_Authn_JwtConfig_Jwks() {}

func (*SseListener_Authn_JwtConfig_RemoteJwks) isSseListener_Authn_JwtConfig_Jwks() {}

var File_listener_proto protoreflect.FileDescriptor

var file_listener_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x19, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x64,
	0x65, 0x76, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x1a, 0x0c, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x72, 0x62, 0x61, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x02, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x48, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x69, 0x73, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x12, 0x3a, 0x0a, 0x03, 0x73, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x64, 0x65, 0x76,
	0x2e, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x73, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x48, 0x00, 0x52, 0x03, 0x73, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x05,
	0x73, 0x74, 0x64, 0x69, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c,
	0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x64, 0x69, 0x6f, 0x4c, 0x69, 0x73,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x64, 0x69, 0x6f, 0x22, 0x1c,
	0x0a, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x43,
	0x50, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x32, 0x41, 0x10, 0x01, 0x42, 0x0a, 0x0a, 0x08,
	0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x22, 0xc4, 0x05, 0x0a, 0x0b, 0x53, 0x73, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x42, 0x0a, 0x03, 0x74, 0x6c, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e,
	0x53, 0x73, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x54, 0x6c, 0x73, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x03, 0x74, 0x6c, 0x73, 0x12, 0x42, 0x0a, 0x05, 0x61, 0x75,
	0x74, 0x68, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x69, 0x73,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x73, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6e, 0x52, 0x05, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x12, 0x32,
	0x0a, 0x04, 0x72, 0x62, 0x61, 0x63, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x64, 0x65, 0x76, 0x2e,
	0x72, 0x62, 0x61, 0x63, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x53, 0x65, 0x74, 0x52, 0x04, 0x72, 0x62,
	0x61, 0x63, 0x1a, 0x93, 0x01, 0x0a, 0x09, 0x54, 0x6c, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x41, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x5f, 0x70, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x28, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x64, 0x65, 0x76, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x6f, 0x63, 0x61,
	0x6c, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x6b, 0x65, 0x79,
	0x50, 0x65, 0x6d, 0x12, 0x43, 0x0a, 0x08, 0x63, 0x65, 0x72, 0x74, 0x5f, 0x70, 0x65, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52,
	0x07, 0x63, 0x65, 0x72, 0x74, 0x50, 0x65, 0x6d, 0x1a, 0xb4, 0x02, 0x0a, 0x05, 0x41, 0x75, 0x74,
	0x68, 0x6e, 0x12, 0x48, 0x0a, 0x03, 0x6a, 0x77, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x36, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x64,
	0x65, 0x76, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x73, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6e, 0x2e, 0x4a, 0x77,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x03, 0x6a, 0x77, 0x74, 0x1a, 0xe0, 0x01, 0x0a,
	0x09, 0x4a, 0x77, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x69, 0x73, 0x73, 0x75,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x49,
	0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x6a, 0x77, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x00, 0x52, 0x09,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x4a, 0x77, 0x6b, 0x73, 0x12, 0x4c, 0x0a, 0x0b, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x5f, 0x6a, 0x77, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x64, 0x65,
	0x76, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x4a, 0x77, 0x6b, 0x73, 0x42, 0x06, 0x0a, 0x04, 0x6a, 0x77, 0x6b, 0x73, 0x22,
	0x0f, 0x0a, 0x0d, 0x53, 0x74, 0x64, 0x69, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x3b,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_listener_proto_rawDescOnce sync.Once
	file_listener_proto_rawDescData = file_listener_proto_rawDesc
)

func file_listener_proto_rawDescGZIP() []byte {
	file_listener_proto_rawDescOnce.Do(func() {
		file_listener_proto_rawDescData = protoimpl.X.CompressGZIP(file_listener_proto_rawDescData)
	})
	return file_listener_proto_rawDescData
}

var file_listener_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_listener_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_listener_proto_goTypes = []interface{}{
	(Listener_Protocol)(0),              // 0: agentgateway.dev.listener.Listener.Protocol
	(*Listener)(nil),                    // 1: agentgateway.dev.listener.Listener
	(*SseListener)(nil),                 // 2: agentgateway.dev.listener.SseListener
	(*StdioListener)(nil),               // 3: agentgateway.dev.listener.StdioListener
	(*SseListener_TlsConfig)(nil),       // 4: agentgateway.dev.listener.SseListener.TlsConfig
	(*SseListener_Authn)(nil),           // 5: agentgateway.dev.listener.SseListener.Authn
	(*SseListener_Authn_JwtConfig)(nil), // 6: agentgateway.dev.listener.SseListener.Authn.JwtConfig
	(*RuleSet)(nil),                     // 7: agentgateway.dev.rbac.RuleSet
	(*LocalDataSource)(nil),             // 8: agentgateway.dev.common.LocalDataSource
	(*RemoteDataSource)(nil),            // 9: agentgateway.dev.common.RemoteDataSource
}
var file_listener_proto_depIdxs = []int32{
	0,  // 0: agentgateway.dev.listener.Listener.protocol:type_name -> agentgateway.dev.listener.Listener.Protocol
	2,  // 1: agentgateway.dev.listener.Listener.sse:type_name -> agentgateway.dev.listener.SseListener
	3,  // 2: agentgateway.dev.listener.Listener.stdio:type_name -> agentgateway.dev.listener.StdioListener
	4,  // 3: agentgateway.dev.listener.SseListener.tls:type_name -> agentgateway.dev.listener.SseListener.TlsConfig
	5,  // 4: agentgateway.dev.listener.SseListener.authn:type_name -> agentgateway.dev.listener.SseListener.Authn
	7,  // 5: agentgateway.dev.listener.SseListener.rbac:type_name -> agentgateway.dev.rbac.RuleSet
	8,  // 6: agentgateway.dev.listener.SseListener.TlsConfig.key_pem:type_name -> agentgateway.dev.common.LocalDataSource
	8,  // 7: agentgateway.dev.listener.SseListener.TlsConfig.cert_pem:type_name -> agentgateway.dev.common.LocalDataSource
	6,  // 8: agentgateway.dev.listener.SseListener.Authn.jwt:type_name -> agentgateway.dev.listener.SseListener.Authn.JwtConfig
	8,  // 9: agentgateway.dev.listener.SseListener.Authn.JwtConfig.local_jwks:type_name -> agentgateway.dev.common.LocalDataSource
	9,  // 10: agentgateway.dev.listener.SseListener.Authn.JwtConfig.remote_jwks:type_name -> agentgateway.dev.common.RemoteDataSource
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_listener_proto_init() }
func file_listener_proto_init() {
	if File_listener_proto != nil {
		return
	}
	file_common_proto_init()
	file_rbac_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_listener_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listener); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listener_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SseListener); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listener_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StdioListener); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listener_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SseListener_TlsConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listener_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SseListener_Authn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listener_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SseListener_Authn_JwtConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_listener_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Listener_Sse)(nil),
		(*Listener_Stdio)(nil),
	}
	file_listener_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*SseListener_Authn_JwtConfig_LocalJwks)(nil),
		(*SseListener_Authn_JwtConfig_RemoteJwks)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_listener_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_listener_proto_goTypes,
		DependencyIndexes: file_listener_proto_depIdxs,
		EnumInfos:         file_listener_proto_enumTypes,
		MessageInfos:      file_listener_proto_msgTypes,
	}.Build()
	File_listener_proto = out.File
	file_listener_proto_rawDesc = nil
	file_listener_proto_goTypes = nil
	file_listener_proto_depIdxs = nil
}
